name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini:ro
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NOMBRE=Santiago
      - CLI_APELLIDO=Lorca
      - CLI_DOCUMENTO=30904465
      - CLI_NACIMIENTO=1999-03-17
      - CLI_NUMERO=7574
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_NOMBRE=María
      - CLI_APELLIDO=Gómez
      - CLI_DOCUMENTO=28456789
      - CLI_NACIMIENTO=1985-07-12
      - CLI_NUMERO=1234
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_NOMBRE=Carlos
      - CLI_APELLIDO=Fernández
      - CLI_DOCUMENTO=33222444
      - CLI_NACIMIENTO=1992-11-02
      - CLI_NUMERO=5678
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_NOMBRE=Lucía
      - CLI_APELLIDO=Martínez
      - CLI_DOCUMENTO=40123456
      - CLI_NACIMIENTO=2000-01-25
      - CLI_NUMERO=9012
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_NOMBRE=Javier
      - CLI_APELLIDO=Pereira
      - CLI_DOCUMENTO=37889900
      - CLI_NACIMIENTO=1995-05-30
      - CLI_NUMERO=3456
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
